name: tera_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.19
  # flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  http: null
  provider: ^6.1.2
  routemaster: ^1.0.1
  shared_preferences: ^2.2.3
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri.ttf
